version: '3'
services:
  solr:
    image: solr:9.0
    ports:
      - "50000:8983"
    volumes:
      - ./solr/data:/var/solr
      - ./solr/config:/tmp/solr
    command: ["solr-precreate", "moviesdb", "/tmp/solr"]
    container_name: solr

  redis:
    image: redis:7.0-alpine
    ports:
      - "50100:6379"
    container_name: redis
