version: '3'
services:
  solr:
    image: solr:9.0
    ports:
      - "50000:8983"
    volumes:
      - ./solr/data:/var/solr
    command: ["solr-precreate", "moviesdb"]

  redis:
    image: redis:7.0-alpine
    ports:
      - "50001:6379"
